#
# FIRST OFF CHANGE ALL THE CREDENTIALS !!!!
#
# Then run
#
# $ docker-compose up --build
#

version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=ctfpad                                   # (opt.) Change here
      - POSTGRES_USER=ctfpad                                 # (opt.) Change here
      - POSTGRES_PASSWORD=tookahlaiphee2KieTeeg5ooxutang4o   # Change here
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      backend:
    restart: unless-stopped


  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:alpine
    environment:
      - CMD_DB_URL=postgres://ctfpad:tookahlaiphee2KieTeeg5ooxutang4o@db:5432/ctfpad    # Change here
      - CMD_DOMAIN=localhost                                                            # Change here to your server public IP / FQDN
      - CMD_PORT=3000                                                                   # Change here
      - CMD_URL_ADDPORT=true
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_FREEURL=true
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
      # Uncomment to use nginx as a HTTPS reverse proxy
      #- CMD_DOMAIN=hedgedoc.mydomain.com:8443
      #- CMD_URL_ADDPORT=false
      #- CMD_PROTOCOL_USESSL=true
    ports:
      - 3000:3000
    networks:
      backend:
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - hedgedoc-public-uploads:/hedgedoc/public/uploads


  whiteboard:
    image: rofl256/whiteboard:latest
    ports:
      - 3001:8080
    networks:
      backend:
    restart: unless-stopped


  ctfpad:
    build: https://github.com/hugsy/ctfpad.git#master
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=0
      - HEDGEDOC_URL=http://localhost:3000                     # Change here to the CMD_DOMAIN and CMD_PORT defined above in the hedgedoc service
      #- HEDGEDOC_URL=https://hedgedoc.mydomain.com:8443       # or set this to use nginx as a HTTPS reverse proxy
      - WHITEBOARD_URL=http://localhost:3001                   # Change here
      #- WHITEBOARD_URL=https://whiteboard.mydomain.com:8443   # or set this to use nginx as a HTTPS reverse proxy
      - CTFPAD_HOSTNAME=localhost                              # Change here to your server public IP / FQDN
      - CTFPAD_PORT=8000                                       # Change here to your server public port for CTFPad
      - CTFPAD_USE_SSL=0                                       # Change here to 1 if your public server uses https
      - CTFPAD_DB_NAME=ctfpad                                  # (opt.) Change here
      - CTFPAD_DB_USER=ctfpad                                  # (opt.) Change here
      - CTFPAD_DB_PASSWORD=tookahlaiphee2KieTeeg5ooxutang4o    # Change here
      - CTFPAD_DB_HOST=db
      - CTFPAD_DB_PORT=5432
      - CTFPAD_SECRET_KEY=74320c04549af3a5f9fd9bc007b2e20ced8  # Change here
      # Uncomment (and customize) below to enable the password recovery feature by email
      #- CTFPAD_EMAIL_SERVER_HOST=smtp.gmail.com # or mailgun, or sendgrid etc.
      #- CTFPAD_EMAIL_SERVER_PORT=587
      #- CTFPAD_EMAIL_USERNAME=myaccount
      #- CTFPAD_EMAIL_PASSWORD=mypassword
      # Uncomment (and customize) below to enable Discord webhook notifications
      #- CTFPAD_DISCORD_WEBHOOK_URL=
    depends_on:
      - db
      - hedgedoc
      - whiteboard
    ports:
      - 8000:8000
    networks:
      backend:
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads


  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/certs:/etc/nginx/certs
    ports:
      - 8443:8443
    depends_on:
      - ctfpad
    networks:
      backend:
    restart: unless-stopped


networks:
  backend:


volumes:
  db:
  uploads:
  hedgedoc-public-uploads:
